apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: python-pr-validate
spec:
  pipelineSpec:
    tasks:
      - name: from-python-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/python/pullrequest.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - name: jx-variables
              resources: { }
            - name: build-python-validate
              image: shiti/python-poetry:1.0.0
              resources: { }
              env:
                - name: POETRY_DJANGO_SETTINGS_MODULE
                  value: "config.settings.test"
              script: |
                #!/bin/sh
                apt-get install -y libpq-dev gcc
                cd apps/api
                poetry check
                poetry install --no-interaction
                poetry run pylint --init-hook="sys.path.append('.')" --load-plugins pylint_django **/*.py
                poetry run pytest
                cd apps/batch_process
                poetry check
                poetry install --no-interaction
                poetry run pylint --init-hook="sys.path.append('.')" **/*.py
                poetry run pytest
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
