apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: javascript-pr-validate
spec:
  pipelineSpec:
    tasks:
      - name: from-javascript-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          spec: null
          stepTemplate:
            env:
              - name: NPM_CONFIG_USERCONFIG
                value: /tekton/home/npm/.npmrc
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/javascript-ui-nginx/pullrequest.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - name: jx-variables
              resources: {}
            - name: build-npm-validate
              image: node:16-slim
              resources: {}
              script: |
                #!/bin/sh
                cd apps/ui
                npm install
                CI=true DISPLAY=:99 npm test
                npm run build
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
