apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{cookiecutter.project_dir}}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{cookiecutter.project_dir}}
spec:
  hosts:
    - "*"
  gateways:
    - {{cookiecutter.project_dir}}-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{cookiecutter.project_dir}}-service
            port:
              number: 80
    - match:
        - uri:
            prefix: /home
        route:
          - destination:
              host: {{cookiecutter.project_dir}}-ui-service
              port:
                number: 80
